name: Deploy with ECS & CodeDeploy (Manual Trigger)

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform5
        run: terraform init

      - name: Terraform Apply (Infra only)
        working-directory: terraform5
        run: terraform apply -auto-approve

      - name: Register ECS Task Definition from taskdef-v2.json
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://terraform5/taskdef-v2.json

      - name: Trigger CodeDeploy using appspec.json
        run: |
          aws deploy create-deployment \
            --cli-input-json file://terraform5/appspec.json

      - name: Wait before destroy (20 min)
        run: |
          echo "⏳ Waiting 20 minutes before destroying infra..."
          sleep 1200

      - name: Terraform Destroy (Teardown)
        working-directory: terraform5
        run: terraform destroy -auto-approve
